apiVersion: apps/v1
kind: Deployment
metadata:
  name: my_app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my_app
  template:
    metadata:
      labels:
        app: my_app
    spec:
      containers:
      - name: my_app
        image: 182399717976.dkr.ecr.us-east-1.amazonaws.com/my_app:latest
        ports:
        - containerPort: 3000