apiVersion: v1
kind: Service
metadata:
  name: my_app_service
spec:
  selector:
    app: my_app
  ports:
    - protocol: TCP
      port: 80          # Exposed by service
      targetPort: 3000  # Container port